default_install_hook_types: [pre-push]
exclude: ^dist/
repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/biomejs/pre-commit
    rev: 16e7f97478690d1e4fab107fcab1c56f0080d28b  # frozen: v2.5.0
    hooks:
      - id: biome-check
