default_install_hook_types: [pre-push]
exclude: ^dist/
repos:
  - repo: builtin
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/biomejs/pre-commit
    rev: 4b413f3670a174f31451d158949f7a5938352eff  # frozen: v2.5.1
    hooks:
      - id: biome-check
