name: prek-action
description: Run pre-commit hooks using prek
inputs:
  extra_args:
    description: Options to pass to `prek run`
    required: false
    default: '--all-files'
runs:
  using: composite
  steps:
  - name: Install prek
    run: python -m pip install prek
    shell: bash
  - uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
    with:
      path: ~/.cache/prek
      key: prek-v1|${{ runner.os }}|${{ runner.arch }}|${{ hashFiles('**/.pre-commit-config.yaml') }}
  - run: prek run --show-diff-on-failure --color=always ${{ inputs.extra_args }}
    shell: bash
branding:
  icon: 'git-commit'
  color: 'orange'
