name: prek-action
description: Run pre-commit hooks using prek
inputs:
  extra-args:
    description: Options to pass to `prek run`
    required: false
    default: '--all-files'
  extra_args:
    description: Options to pass to `prek run` (deprecated, use extra-args)
    required: false
  install-only:
    description: Only install prek, do not run it
    required: false
    default: 'false'
  prek-version:
    description: Version of prek to install (e.g., '0.2.1', 'latest')
    required: false
    default: 'latest'
  working-directory:
    description: The working directory to run prek in
    required: false
    default: '.'
outputs:
  prek-version:
    description: The version of prek that was installed
    value: ${{ steps.resolve.outputs.version }}
runs:
  using: composite
  steps:
  - name: Resolve version
    id: resolve
    run: |
      if [[ "${PREK_VERSION}" = "latest" ]]; then
        PREK_VERSION=$(gh api repos/j178/prek/releases/latest --jq '.tag_name')
      fi
      VERSION="${PREK_VERSION#v}"
      VERSION="v${VERSION}"
      echo "version=${VERSION}" >> $GITHUB_OUTPUT
    shell: bash
    env:
      PREK_VERSION: ${{ inputs.prek-version }}
      GH_TOKEN: ${{ github.token }}
  - name: Install prek
    run: |
      echo "::group::Installing prek ${PREK_VERSION}"
      curl --proto '=https' --tlsv1.2 -LsSf https://github.com/j178/prek/releases/download/${PREK_VERSION}/prek-installer.sh | sh
      echo "::endgroup::"
    shell: bash
    if: runner.os != 'Windows'
    env:
      PREK_VERSION: ${{ steps.resolve.outputs.version }}
  - name: Install prek (Windows)
    run: |
      Write-Host "::group::Installing prek $env:PREK_VERSION"
      irm https://github.com/j178/prek/releases/download/$env:PREK_VERSION/prek-installer.ps1 | iex
      Write-Host "::endgroup::"
    shell: powershell
    if: runner.os == 'Windows'
    env:
      PREK_VERSION: ${{ steps.resolve.outputs.version }}
  - name: Setup cache
    uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
    with:
      path: |
        ~/.cache/prek
        ~\AppData\Local\prek
      key: prek-v1|${{ runner.os }}|${{ runner.arch }}|${{ hashFiles(format('{0}/**/.pre-commit-config.yaml', inputs.working-directory)) }}
    if: inputs.install-only == 'false'
  - name: Run prek
    run: |
      import shlex
      import sys
      import os

      sys.stdout.reconfigure(encoding='utf-8')
      sys.stderr.reconfigure(encoding='utf-8')

      cmd = ['prek', 'run', '--show-diff-on-failure', '--color=always']

      extra_args = os.environ['EXTRA_ARGS']
      if extra_args:
          try:
              parsed_args = shlex.split(extra_args)
              cmd.extend(parsed_args)
          except ValueError as e:
              print(f'Error parsing extra-args: {e}', file=sys.stderr)
              sys.exit(1)

      os.execvp(cmd[0], cmd)

    shell: python
    working-directory: ${{ inputs.working-directory }}
    if: inputs.install-only == 'false'
    env:
      EXTRA_ARGS: ${{ inputs.extra_args || inputs.extra-args }}
  - name: Show verbose logs
    run: |
      echo "::group::Prek verbose logs"
      log="$(prek cache dir)/prek.log"
      cat "$log" || echo "No prek log file found at $log"
      echo "::endgroup::"
    shell: bash
    if: inputs.install-only == 'false' && always()
  - name: Setup tmate session
    uses: mxschmitt/action-tmate@v3
branding:
  icon: 'git-commit'
  color: 'orange'
